name       : kcalendarcore
version    : 5.67.0
release    : 5
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.67/kcalendarcore-5.67.0.tar.xz : b24642e98a0c2459a543eb910e7e964c04724816e52568ab1decbf19ea54fff4
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install
