name       : kcalendarcore
version    : 5.64.0
release    : 2
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.64/kcalendarcore-5.64.0.tar.xz : 983f240a7478a780dc403d577827f027856f9f67e8c3bfe8b69d56093e5bb80e
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5Core)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install
