name       : kcalendarcore
version    : 5.63.0
release    : 1
source     :
    - https://origin.download.kde.org/stable/frameworks/5.63/kcalendarcore-5.63.0.tar.xz : 43dfecd3dfd0f44ee3e0029613561822f3dd3b3145b52c4dd3e72b67dae518b3
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5Core)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install