name       : kcalendarcore
version    : 5.76.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.76/kcalendarcore-5.76.0.tar.xz : e6fd390b8ba2a899e7abda3de8d9ab7e5155fede6bbee9ca2b302b931a0232ae
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install
