name       : kcalendarcore
version    : 5.72.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.72/kcalendarcore-5.72.0.tar.xz : af76009fdf12e8bda7fc72ece3ea1c183f5ed074930538f786c4fce2a2c20a95
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install
