name       : kcalendarcore
version    : 5.81.0
release    : 19
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/kcalendarcore-5.81.0.tar.xz : bac828b363a7b406b3ccdc98854fb3ebd4d06b503c298dc676215a4612451529
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5UiTools)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
