name       : kcalendarcore
version    : 5.74.0
release    : 11
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.74/kcalendarcore-5.74.0.tar.xz : 003cb076e3094d8327049f776b176ea1c1365f810e3dc8d245938b6c76598e82
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install
