name       : kcalendarcore
version    : 5.84.0
release    : 22
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.84/kcalendarcore-5.84.0.tar.xz : 8b116cf5dff328597b74a550a938ce3e3a64fcbf7022c692b07691a9dbf35a19
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5UiTools)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
rundeps    :
    - devel :
        - extra-cmake-modules
        - qt5-tools-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
