name       : kcalendarcore
version    : 5.75.0
release    : 12
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.75/kcalendarcore-5.75.0.tar.xz : 02ff08c6462a5f0552c85a1da98320ca0a1c8d7295a05230f4b27b7a3f0a3dbc
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install
