name       : kcalendarcore
version    : 5.69.0
release    : 7
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.69/kcalendarcore-5.69.0.tar.xz : 4ef44809c4766843f71b908eafa66d2b00047984c47abe8c62c80f06a2cc2184
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : desktop.library
summary    : Provides access to and handling of calendar data
description: |
    This library provides access to and handling of calendar data. It supports the standard formats iCalendar and vCalendar and the group scheduling standard iTIP.
builddeps  :
    - pkgconfig(Qt5UiTools)
    - db5-devel
    - extra-cmake-modules
    - libical-devel
replaces   :
    - kcalcore
    - devel : kcalcore-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install
